import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { getTelegramUser } from '../lib/platform'

export type AppLanguage = 'ru' | 'en'

interface LanguageContextValue {
  language: AppLanguage
  detectedLanguage: AppLanguage
  setLanguage: (language: AppLanguage) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const STORAGE_KEY = 'antigram:language'
const LanguageContext = createContext<LanguageContextValue | null>(null)

const translations: Record<AppLanguage, Record<string, string>> = {
  ru: {
    'common.anonymous': 'Аноним',
    'common.someone': 'Кто-то',
    'common.back': 'Назад',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.save': 'Сохранить',
    'common.saving': 'Сохраняем...',
    'common.close': 'Закрыть',
    'common.open': 'Открыть',
    'common.loading': 'Загружаем...',
    'common.signIn': 'Войти',
    'common.signingIn': 'Входим...',
    'common.search': 'Поиск',
    'common.searchPeople': 'Поиск людей...',
    'common.searchAntigram': 'Поиск людей и моментов...',
    'common.notFound': 'Ничего не найдено',
    'common.error': 'Произошла ошибка',
    'common.done': 'Готово',
    'common.profile': 'Профиль',
    'common.photo': 'фото',
    'common.file': 'файл',
    'common.none': 'Без',
    'common.noFilter': 'Без фильтра',

    'time.now': 'только что',
    'time.minutesAgo': '{{count}} мин назад',
    'time.hoursAgo': '{{count}} ч назад',
    'time.yesterday': 'вчера',
    'time.daysAgo': '{{count}} д назад',

    'emotion.warm': 'Тепло',
    'emotion.nostalgic': 'Ностальгия',
    'emotion.calm': 'Спокойно',
    'emotion.wow': 'Вау',
    'emotion.relatable': 'Близко',
    'emotion.custom': 'Своя',
    'category.forYou': 'Для вас',

    'auth.tagline': 'Реальные моменты, настоящие эмоции',
    'auth.loginAs': 'Войти как {{name}}',
    'auth.telegramUser': 'пользователь Telegram',
    'auth.or': 'или',
    'auth.name': 'Имя',
    'auth.namePlaceholder': 'Как тебя зовут',
    'auth.password': 'Пароль',
    'auth.passwordPlaceholder': 'Минимум 6 символов',
    'auth.newPassword': 'Новый пароль',
    'auth.confirmPassword': 'Повторите пароль',
    'auth.emailLogin': 'Войти по email',
    'auth.createAccount': 'Создать аккаунт',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.sendResetLink': 'Отправить ссылку',
    'auth.updatePassword': 'Обновить пароль',
    'auth.resetEmailSent': 'Если email привязан к аккаунту, мы отправили ссылку для восстановления.',
    'auth.resetLinkInvalid': 'Ссылка восстановления недействительна или устарела. Запросите новую.',
    'auth.passwordMismatch': 'Пароли должны совпадать и быть минимум 6 символов.',
    'auth.passwordUpdated': 'Пароль обновлён',
    'auth.noAccount': 'Нет аккаунта? Зарегистрироваться',
    'auth.hasAccount': 'Уже есть аккаунт? Войти',
    'auth.termsPrefix': 'Продолжая, вы принимаете',
    'auth.terms': 'условия',
    'auth.and': 'и',
    'auth.privacy': 'политику конфиденциальности',

    'feed.photoOfDay': 'Фото дня',
    'feed.emptyFollowing': 'Пока нет моментов.\nПодпишитесь на людей, чтобы увидеть их.',
    'feed.emptyEmotion': 'Нет постов с такой эмоцией.',

    'explore.title': 'Подборки',
    'explore.emptyEmotion': 'Нет постов с такой эмоцией.',
    'search.people': 'Люди',
    'search.albums': 'Альбомы',
    'search.moments': 'Моменты',
    'search.moods': 'Настроения',

    'notifications.title': 'Уведомления',
    'notifications.signIn': 'Войдите, чтобы видеть уведомления',
    'notifications.empty': 'Пока нет уведомлений',
    'notifications.follow': '{{actor}} подписался на вас',
    'notifications.reaction': '{{actor}} отреагировал: {{reaction}}',
    'notifications.reactionFallback': '{{actor}} отреагировал на ваш момент',
    'notifications.commentFallback': '{{actor}} прокомментировал ваш момент',

    'profile.notFound': 'Профиль не найден',
    'profile.posts': 'постов',
    'profile.frames': 'кадры',
    'profile.followers': 'подписчики',
    'profile.following': 'подписки',
    'profile.follow': 'Подписаться',
    'profile.unfollow': 'Отписаться',
    'profile.block': 'Заблокировать',
    'profile.unblock': 'Разблокировать',
    'profile.blocked': 'Пользователь заблокирован. Его кадры скрыты из ваших лент и поиска.',
    'profile.blockedBy': 'Этот профиль сейчас недоступен.',
    'profile.blockFailed': 'Не удалось заблокировать пользователя',
    'profile.unblockFailed': 'Не удалось разблокировать пользователя',
    'profile.report': 'Пожаловаться',
    'profile.reportFailed': 'Не удалось отправить жалобу',
    'profile.reportSent': 'Жалоба отправлена',
    'profile.edit': 'Редактировать профиль',
    'profile.noMoments': 'Нет моментов',
    'profile.mine': 'Мой профиль',
    'profile.signInPrompt': 'Войдите, чтобы увидеть свой профиль',
    'profile.pickFilmPhotos': 'Выберите 5 фото для плёнки — нажмите + на кадр',
    'profile.myFrames': 'Мои кадры',
    'profile.myAlbums': 'Мои альбомы',
    'profile.pickPhotoSlot': 'Выберите фото (слот {{slot}})',
    'profile.fromMyFrames': 'Из моих кадров',
    'profile.noPublishedFrames': 'Нет опубликованных кадров',
    'profile.newAlbum': 'Новый альбом',
    'profile.albumTitlePlaceholder': 'Название...',
    'profile.create': 'Создать',
    'profile.saved': 'Сохранённые',
    'profile.newFilm': 'Новая плёнка',
    'profile.framesCount': '{{count}} кадров',
    'profile.deleteFrame': 'Удалить кадр',
    'profile.savedToast': 'Сохранено',
    'profile.saveError': 'Ошибка сохранения',
    'profile.photoAdded': 'Фото добавлено в плёнку',

    'settings.title': 'Настройки',
    'settings.name': 'Имя',
    'settings.username': 'Имя пользователя',
    'settings.website': 'Вебсайт',
    'settings.info': 'Инфо',
    'settings.aboutPlaceholder': 'О себе...',
    'settings.language': 'Язык / Language',
    'settings.languageAuto': 'По умолчанию: {{language}} по языку Telegram/устройства.',
    'settings.account': 'Аккаунт',
    'settings.changePassword': 'Сменить пароль',
    'settings.loginEmail': 'Email для входа',
    'settings.loginPassword': 'Пароль для входа',
    'settings.linkLogin': 'Привязать email и пароль',
    'settings.loginLinked': 'Email и пароль привязаны к этому аккаунту',
    'settings.loginLinkFailed': 'Не удалось привязать email и пароль',
    'settings.loginPasswordHint': 'Введите email и пароль минимум 6 символов',
    'settings.loginPasswordTelegramHint': 'Telegram-вход останется. Email и пароль позволят входить в этот же аккаунт вне Telegram.',
    'settings.loginPasswordEmailHint': 'Обновите email и пароль для входа в этот аккаунт.',
    'settings.rulesSupport': 'Правила и поддержка',
    'settings.inviteFriend': 'Пригласить друга',
    'settings.help': 'Помощь',
    'settings.supportInbox': 'Чат поддержки',
    'settings.moderation': 'Модерация',
    'settings.premium': 'Antigram Premium',
    'settings.termsStars': 'Условия и Stars',
    'settings.privacy': 'Политика конфиденциальности',
    'settings.signOut': 'Выйти из аккаунта',
    'settings.signOutQuestion': 'Выйти из аккаунта?',
    'settings.signOutHint': 'Вы можете войти снова в любое время',
    'settings.langRussian': 'русский',
    'settings.langEnglish': 'English',

    'support.helpTitle': 'Помощь',
    'support.helpHint': 'Пожалуйста, опишите максимально подробно Вашу ситуацию и оставьте контакты для связи',
    'support.placeholder': 'Что случилось?',
    'support.attachFile': 'Прикрепить файл',
    'support.send': 'Отправить',
    'support.sending': 'Отправляем...',
    'support.sent': 'Отправлено',
    'support.fileTooLarge': 'Файл больше 8 МБ',
    'support.needTextOrFile': 'Опиши проблему или прикрепи файл',
    'support.sendFailed': 'Не удалось отправить обращение',
    'support.inboxTitle': 'Чат поддержки',
    'support.inboxHint': 'Обращения пользователей',
    'support.empty': 'Пока нет обращений',
    'support.user': 'Пользователь',
    'support.openStatus': 'новое',
    'support.closedStatus': 'закрыто',
    'support.noText': '(без текста)',
    'support.attachment': 'Вложение: {{name}}',
    'support.closeRequest': 'Закрыть',
    'support.openRequest': 'Открыть',
    'support.loadFailed': 'Не удалось загрузить обращения',
    'support.openAttachmentFailed': 'Не удалось открыть вложение',
    'support.updateFailed': 'Не удалось обновить статус',

    'moderation.title': 'Модерация',
    'moderation.adminOnly': 'Этот раздел доступен только администраторам.',
    'moderation.empty': 'Жалоб нет',
    'moderation.actionFailed': 'Не удалось выполнить действие',
    'moderation.profile': 'профиль',
    'moderation.moment': 'кадр',
    'moderation.reportType': 'Жалоба: {{type}}',
    'moderation.reporter': 'отправитель',
    'moderation.reportedUser': 'пользователь',
    'moderation.reason': 'Причина',
    'moderation.openMoment': 'Открыть кадр',
    'moderation.markReviewed': 'Проверено',
    'moderation.dismiss': 'Отклонить',
    'moderation.deleteMoment': 'Удалить кадр',
    'moderation.banUser': 'Забанить',
    'moderation.status.open': 'открытые',
    'moderation.status.reviewed': 'проверено',
    'moderation.status.dismissed': 'отклонено',
    'moderation.status.actioned': 'приняты меры',
    'moderation.status.all': 'все',
    'moderation.reason.reported': 'Жалоба на кадр',
    'moderation.reason.profile_reported': 'Жалоба на профиль',

    'camera.signInToShoot': 'Войдите, чтобы снимать',
    'camera.retake': 'Переснять',
    'camera.publish': 'Опубликовать',
    'camera.publishing': 'Публикация...',
    'camera.pickMood': 'Выбери эмоцию кадра',
    'camera.limitReached': 'Лимит кадров на сегодня исчерпан',
    'camera.premiumLimitHint': 'Кадры закончились. В Premium будет 8 кадров в день.',
    'camera.premiumOpen': 'Посмотреть Premium',
    'camera.publishError': 'Ошибка при публикации',
    'camera.noCameraAccess': 'Нет доступа к камере',
    'camera.captureFailed': 'Не удалось снять кадр',
    'camera.allow': 'Разрешить',
    'camera.light': 'СВЕТ',
    'camera.framesResetMidnight': 'кадры обновятся в полночь',
    'camera.framesToday': '{{remaining}} из {{limit}} кадров сегодня',
    'camera.capturing': 'Снимаем кадр',
    'camera.holdingMoment': 'держим момент на плёнке',
    'camera.developing': 'Плёнка проявляется',
    'camera.developingHint': 'Кадр сохранился. Через мгновение он появится в ленте.',
    'camera.shareTitle': 'Кадр готов',
    'camera.shareHint': 'Можно сразу отправить его в чат или сторис Telegram.',
    'camera.shareChat': 'В чат',
    'camera.shareStory': 'В сторис',
    'camera.openFeed': 'В ленту',
    'camera.inviteFriend': 'Пригласить друга',
    'camera.atmosphere': '✦ Атмосфера',
    'camera.customEmotion': 'Своя эмоция',
    'camera.customEmotionHint': 'Выбери эмодзи и назови её',
    'camera.customEmotionPlaceholder': 'Нежно, Дерзко...',
    'camera.add': 'Добавить',
    'camera.captionPlaceholder': 'Добавь подпись...',

    'albums.album': 'Альбом',
    'albums.rename': 'Переименовать',
    'albums.deleteAlbum': 'Удалить альбом',
    'albums.addPhoto': '+ Добавить фото',
    'albums.empty': 'Альбом пуст',
    'albums.remove': 'Убрать',
    'albums.deleteAlbumQuestion': 'Удалить альбом?',
    'albums.deleteAlbumHint': 'Фотографии останутся в ленте',
    'albums.allAdded': 'Все фото уже добавлены',

    'moment.notFound': 'Момент не найден',
    'moment.deleteQuestion': 'Удалить кадр?',
    'moment.deleteHint': 'Это действие нельзя отменить',
    'moment.reaction': 'Реакция',
    'moment.download': 'Скачать фото',
    'moment.openingPhoto': 'Открываем сохранение...',
    'moment.share': 'Поделиться',
    'moment.linkCopied': 'Ссылка скопирована',
    'moment.shareSent': 'Открываем Telegram',
    'moment.addToAlbum': 'Добавить в альбом',
    'moment.addedToAlbum': 'Добавлено в альбом',
    'moment.noAlbums': 'Нет альбомов',
    'moment.report': 'Пожаловаться',
    'moment.reportSignIn': 'Войдите, чтобы пожаловаться',
    'moment.reportFailed': 'Не удалось отправить жалобу',
    'moment.reportSent': 'Жалоба отправлена',
    'moment.blockUser': 'Заблокировать автора',
    'moment.blockSignIn': 'Войдите, чтобы заблокировать автора',
    'moment.blockFailed': 'Не удалось заблокировать автора',
    'moment.userBlocked': 'Автор заблокирован',
    'moment.adminDelete': '🛡 Удалить (Admin)',
    'moment.adminShadowBan': '🛡 Теневой бан',
    'moment.shadowBanned': 'Пользователь в теневом бане',

    'follow.followers': 'Подписчики',
    'follow.following': 'Подписки',
    'follow.emptyFollowers': 'Пока никто не подписался',
    'follow.emptyFollowing': 'Пока нет подписок',
    'follow.onlyYou': 'Видно только вам',
    'follow.signIn': 'Войдите, чтобы видеть свои подписки',
    'follow.profileFallback': 'Профиль Antigram',

    'stars.supportFrame': 'Поддержать кадр',
    'stars.supportRating': 'Stars увеличивают рейтинг кадра и автора в Antigram.',
    'stars.termsNote': 'Это добровольная поддержка и статус внутри приложения. Возможные выплаты, бонусы или premium-функции могут появиться позже отдельной программой и сейчас не гарантируются.',
    'stars.termsLink': 'условия',
    'stars.success': 'Готово. Звезды засчитаны кадру.',
    'stars.accepted': 'Платеж принят. Счетчик обновится чуть позже.',
    'stars.cancelled': 'Оплата отменена.',
    'stars.invoiceOpened': 'Счет открыт. После оплаты Stars появятся у кадра.',
    'stars.finishFailed': 'Не удалось завершить оплату. Попробуйте еще раз.',
    'stars.createFailed': 'Не получилось создать счет. Попробуйте позже.',
    'stars.aria': 'Поддержать кадр Stars, сейчас {{total}}',

    'premium.title': 'Antigram Premium',
    'premium.subtitle': 'Скоро будет доступен за {{price}} Stars / {{days}} дней',
    'premium.comingSoon': 'Скоро доступно',
    'premium.active': 'Активен',
    'premium.activeNoDate': 'активен',
    'premium.activeSubtitle': 'Premium активен до {{date}}. Сейчас доступно {{frames}} кадров в день и {{highlights}} кадров в плёнке профиля.',
    'premium.buy': 'Купить за {{price}} Stars',
    'premium.note': 'Premium будет оплачиваться через Telegram Stars. До запуска покупка недоступна.',
    'premium.profileTitle': 'Premium',
    'premium.profileHint': 'Больше кадров, редкие плёнки и ранний доступ.',
    'premium.profileCompactHint': 'Больше кадров и плёнок',
    'premium.activeCompactHint': 'Ваш расширенный доступ активен',
    'premium.open': 'Подробнее',
    'premium.feature.frames': '8 кадров в день вместо 4',
    'premium.feature.films': 'Редкие плёнки и фильтры',
    'premium.feature.highlights': 'До 10 кадров в плёнке профиля',
    'premium.feature.badge': 'Premium-бейдж в профиле',
    'premium.feature.early': 'Ранний доступ к новым функциям',
    'premium.feature.support': 'Приоритетная поддержка',

    'music.enable': 'Включить музыку',
    'music.close': 'Закрыть плеер',
    'music.previous': 'Предыдущий трек',
    'music.pause': 'Пауза',
    'music.play': 'Играть',
    'music.next': 'Следующий трек',

    'filmPicker.title': 'Зарядить плёнку',
    'filmPicker.hint': 'Выберите плёнку для съёмки',
    'filmPicker.load': 'Зарядить',
    'filmHeader.open': 'Открыть',
    'filmHeader.replace': 'Заменить',
    'filmHeader.remove': 'Убрать',
  },
  en: {
    'common.anonymous': 'Anonymous',
    'common.someone': 'Someone',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.loading': 'Loading...',
    'common.signIn': 'Sign in',
    'common.signingIn': 'Signing in...',
    'common.search': 'Search',
    'common.searchPeople': 'Search people...',
    'common.searchAntigram': 'Search people and moments...',
    'common.notFound': 'Nothing found',
    'common.error': 'Something went wrong',
    'common.done': 'Done',
    'common.profile': 'Profile',
    'common.photo': 'photo',
    'common.file': 'file',
    'common.none': 'None',
    'common.noFilter': 'No filter',

    'time.now': 'just now',
    'time.minutesAgo': '{{count}} min ago',
    'time.hoursAgo': '{{count}} h ago',
    'time.yesterday': 'yesterday',
    'time.daysAgo': '{{count}} d ago',

    'emotion.warm': 'Warm',
    'emotion.nostalgic': 'Nostalgic',
    'emotion.calm': 'Calm',
    'emotion.wow': 'Wow',
    'emotion.relatable': 'Close',
    'emotion.custom': 'Custom',
    'category.forYou': 'For you',

    'auth.tagline': 'Real moments, honest emotions',
    'auth.loginAs': 'Continue as {{name}}',
    'auth.telegramUser': 'Telegram user',
    'auth.or': 'or',
    'auth.name': 'Name',
    'auth.namePlaceholder': 'What should we call you?',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.newPassword': 'New password',
    'auth.confirmPassword': 'Repeat password',
    'auth.emailLogin': 'Sign in with email',
    'auth.createAccount': 'Create account',
    'auth.forgotPassword': 'Forgot password?',
    'auth.sendResetLink': 'Send reset link',
    'auth.updatePassword': 'Update password',
    'auth.resetEmailSent': 'If this email is linked to an account, we sent a recovery link.',
    'auth.resetLinkInvalid': 'This recovery link is invalid or expired. Request a new one.',
    'auth.passwordMismatch': 'Passwords must match and be at least 6 characters.',
    'auth.passwordUpdated': 'Password updated',
    'auth.noAccount': 'No account? Sign up',
    'auth.hasAccount': 'Already have an account? Sign in',
    'auth.termsPrefix': 'By continuing, you accept the',
    'auth.terms': 'terms',
    'auth.and': 'and',
    'auth.privacy': 'privacy policy',

    'feed.photoOfDay': 'Photo of the day',
    'feed.emptyFollowing': 'No moments yet.\nFollow people to see them here.',
    'feed.emptyEmotion': 'No posts with this emotion.',

    'explore.title': 'Collections',
    'explore.emptyEmotion': 'No posts with this emotion.',
    'search.people': 'People',
    'search.albums': 'Albums',
    'search.moments': 'Moments',
    'search.moods': 'Moods',

    'notifications.title': 'Notifications',
    'notifications.signIn': 'Sign in to see notifications',
    'notifications.empty': 'No notifications yet',
    'notifications.follow': '{{actor}} followed you',
    'notifications.reaction': '{{actor}} reacted: {{reaction}}',
    'notifications.reactionFallback': '{{actor}} reacted to your moment',
    'notifications.commentFallback': '{{actor}} commented on your moment',

    'profile.notFound': 'Profile not found',
    'profile.posts': 'posts',
    'profile.frames': 'frames',
    'profile.followers': 'followers',
    'profile.following': 'following',
    'profile.follow': 'Follow',
    'profile.unfollow': 'Unfollow',
    'profile.block': 'Block',
    'profile.unblock': 'Unblock',
    'profile.blocked': 'User blocked. Their frames are hidden from your feeds and search.',
    'profile.blockedBy': 'This profile is not available right now.',
    'profile.blockFailed': 'Could not block user',
    'profile.unblockFailed': 'Could not unblock user',
    'profile.report': 'Report',
    'profile.reportFailed': 'Could not send report',
    'profile.reportSent': 'Report sent',
    'profile.edit': 'Edit profile',
    'profile.noMoments': 'No moments',
    'profile.mine': 'My profile',
    'profile.signInPrompt': 'Sign in to see your profile',
    'profile.pickFilmPhotos': 'Pick 5 photos for the film strip — tap + on a frame',
    'profile.myFrames': 'My frames',
    'profile.myAlbums': 'My albums',
    'profile.pickPhotoSlot': 'Choose photo (slot {{slot}})',
    'profile.fromMyFrames': 'From my frames',
    'profile.noPublishedFrames': 'No published frames',
    'profile.newAlbum': 'New album',
    'profile.albumTitlePlaceholder': 'Title...',
    'profile.create': 'Create',
    'profile.saved': 'Saved',
    'profile.newFilm': 'New film',
    'profile.framesCount': '{{count}} frames',
    'profile.deleteFrame': 'Delete frame',
    'profile.savedToast': 'Saved',
    'profile.saveError': 'Save failed',
    'profile.photoAdded': 'Photo added to film strip',

    'settings.title': 'Settings',
    'settings.name': 'Name',
    'settings.username': 'Username',
    'settings.website': 'Website',
    'settings.info': 'Info',
    'settings.aboutPlaceholder': 'About you...',
    'settings.language': 'Language',
    'settings.languageAuto': 'Default: {{language}} from Telegram/device language.',
    'settings.account': 'Account',
    'settings.changePassword': 'Change password',
    'settings.loginEmail': 'Login email',
    'settings.loginPassword': 'Login password',
    'settings.linkLogin': 'Link email and password',
    'settings.loginLinked': 'Email and password are linked to this account',
    'settings.loginLinkFailed': 'Could not link email and password',
    'settings.loginPasswordHint': 'Enter an email and a password of at least 6 characters',
    'settings.loginPasswordTelegramHint': 'Telegram login will stay available. Email and password let you enter this same account outside Telegram.',
    'settings.loginPasswordEmailHint': 'Update the email and password for this account.',
    'settings.rulesSupport': 'Rules and support',
    'settings.inviteFriend': 'Invite a friend',
    'settings.help': 'Help',
    'settings.supportInbox': 'Support inbox',
    'settings.moderation': 'Moderation',
    'settings.premium': 'Antigram Premium',
    'settings.termsStars': 'Terms and Stars',
    'settings.privacy': 'Privacy policy',
    'settings.signOut': 'Sign out',
    'settings.signOutQuestion': 'Sign out?',
    'settings.signOutHint': 'You can sign in again anytime',
    'settings.langRussian': 'Russian',
    'settings.langEnglish': 'English',

    'support.helpTitle': 'Help',
    'support.helpHint': 'Please describe your situation in as much detail as possible and leave contact details',
    'support.placeholder': 'What happened?',
    'support.attachFile': 'Attach file',
    'support.send': 'Send',
    'support.sending': 'Sending...',
    'support.sent': 'Sent',
    'support.fileTooLarge': 'File is larger than 8 MB',
    'support.needTextOrFile': 'Describe the issue or attach a file',
    'support.sendFailed': 'Could not send request',
    'support.inboxTitle': 'Support inbox',
    'support.inboxHint': 'User requests',
    'support.empty': 'No requests yet',
    'support.user': 'User',
    'support.openStatus': 'new',
    'support.closedStatus': 'closed',
    'support.noText': '(no text)',
    'support.attachment': 'Attachment: {{name}}',
    'support.closeRequest': 'Close',
    'support.openRequest': 'Reopen',
    'support.loadFailed': 'Could not load requests',
    'support.openAttachmentFailed': 'Could not open attachment',
    'support.updateFailed': 'Could not update status',

    'moderation.title': 'Moderation',
    'moderation.adminOnly': 'This section is available to admins only.',
    'moderation.empty': 'No reports',
    'moderation.actionFailed': 'Could not complete action',
    'moderation.profile': 'profile',
    'moderation.moment': 'frame',
    'moderation.reportType': 'Report: {{type}}',
    'moderation.reporter': 'reporter',
    'moderation.reportedUser': 'user',
    'moderation.reason': 'Reason',
    'moderation.openMoment': 'Open frame',
    'moderation.markReviewed': 'Reviewed',
    'moderation.dismiss': 'Dismiss',
    'moderation.deleteMoment': 'Delete frame',
    'moderation.banUser': 'Ban user',
    'moderation.status.open': 'open',
    'moderation.status.reviewed': 'reviewed',
    'moderation.status.dismissed': 'dismissed',
    'moderation.status.actioned': 'actioned',
    'moderation.status.all': 'all',
    'moderation.reason.reported': 'Frame report',
    'moderation.reason.profile_reported': 'Profile report',

    'camera.signInToShoot': 'Sign in to shoot',
    'camera.retake': 'Retake',
    'camera.publish': 'Publish',
    'camera.publishing': 'Publishing...',
    'camera.pickMood': 'Choose a frame emotion',
    'camera.limitReached': 'Daily frame limit reached',
    'camera.premiumLimitHint': 'You are out of frames. Premium will include 8 frames per day.',
    'camera.premiumOpen': 'View Premium',
    'camera.publishError': 'Publishing failed',
    'camera.noCameraAccess': 'No camera access',
    'camera.captureFailed': 'Could not capture frame',
    'camera.allow': 'Allow',
    'camera.light': 'LIGHT',
    'camera.framesResetMidnight': 'frames reset at midnight',
    'camera.framesToday': '{{remaining}} of {{limit}} frames today',
    'camera.capturing': 'Capturing frame',
    'camera.holdingMoment': 'holding the moment on film',
    'camera.developing': 'Film is developing',
    'camera.developingHint': 'Your frame is saved. It will appear in the feed in a moment.',
    'camera.shareTitle': 'Frame is ready',
    'camera.shareHint': 'Send it to a Telegram chat or story right away.',
    'camera.shareChat': 'To chat',
    'camera.shareStory': 'To story',
    'camera.openFeed': 'Open feed',
    'camera.inviteFriend': 'Invite a friend',
    'camera.atmosphere': '✦ Atmosphere',
    'camera.customEmotion': 'Custom emotion',
    'camera.customEmotionHint': 'Choose an emoji and name it',
    'camera.customEmotionPlaceholder': 'Soft, Bold...',
    'camera.add': 'Add',
    'camera.captionPlaceholder': 'Add a caption...',

    'albums.album': 'Album',
    'albums.rename': 'Rename',
    'albums.deleteAlbum': 'Delete album',
    'albums.addPhoto': '+ Add photo',
    'albums.empty': 'Album is empty',
    'albums.remove': 'Remove',
    'albums.deleteAlbumQuestion': 'Delete album?',
    'albums.deleteAlbumHint': 'Photos will stay in the feed',
    'albums.allAdded': 'All photos are already added',

    'moment.notFound': 'Moment not found',
    'moment.deleteQuestion': 'Delete frame?',
    'moment.deleteHint': 'This action cannot be undone',
    'moment.reaction': 'Reaction',
    'moment.download': 'Download photo',
    'moment.openingPhoto': 'Opening save...',
    'moment.share': 'Share',
    'moment.linkCopied': 'Link copied',
    'moment.shareSent': 'Opening Telegram',
    'moment.addToAlbum': 'Add to album',
    'moment.addedToAlbum': 'Added to album',
    'moment.noAlbums': 'No albums',
    'moment.report': 'Report',
    'moment.reportSignIn': 'Sign in to report',
    'moment.reportFailed': 'Could not send report',
    'moment.reportSent': 'Report sent',
    'moment.blockUser': 'Block author',
    'moment.blockSignIn': 'Sign in to block author',
    'moment.blockFailed': 'Could not block author',
    'moment.userBlocked': 'Author blocked',
    'moment.adminDelete': '🛡 Delete (Admin)',
    'moment.adminShadowBan': '🛡 Shadow ban',
    'moment.shadowBanned': 'User is shadow banned',

    'follow.followers': 'Followers',
    'follow.following': 'Following',
    'follow.emptyFollowers': 'No followers yet',
    'follow.emptyFollowing': 'Not following anyone yet',
    'follow.onlyYou': 'Visible only to you',
    'follow.signIn': 'Sign in to see your follows',
    'follow.profileFallback': 'Antigram profile',

    'stars.supportFrame': 'Support frame',
    'stars.supportRating': 'Stars increase the frame and author rating in Antigram.',
    'stars.termsNote': 'This is voluntary support and status inside the app. Possible payouts, bonuses, or premium features may appear later as a separate program and are not guaranteed now.',
    'stars.termsLink': 'terms',
    'stars.success': 'Done. Stars were added to the frame.',
    'stars.accepted': 'Payment accepted. The counter will update shortly.',
    'stars.cancelled': 'Payment cancelled.',
    'stars.invoiceOpened': 'Invoice opened. Stars will appear after payment.',
    'stars.finishFailed': 'Could not finish payment. Try again.',
    'stars.createFailed': 'Could not create invoice. Try later.',
    'stars.aria': 'Support frame with Stars, current total {{total}}',

    'premium.title': 'Antigram Premium',
    'premium.subtitle': 'Coming soon for {{price}} Stars / {{days}} days',
    'premium.comingSoon': 'Coming soon',
    'premium.active': 'Active',
    'premium.activeNoDate': 'active',
    'premium.activeSubtitle': 'Premium is active until {{date}}. You now have {{frames}} frames per day and {{highlights}} frames in the profile strip.',
    'premium.buy': 'Buy for {{price}} Stars',
    'premium.note': 'Premium will be paid through Telegram Stars. Purchases are unavailable until launch.',
    'premium.profileTitle': 'Premium',
    'premium.profileHint': 'More frames, rare films, and early access.',
    'premium.profileCompactHint': 'More frames and films',
    'premium.activeCompactHint': 'Your expanded access is active',
    'premium.open': 'Learn more',
    'premium.feature.frames': '8 frames per day instead of 4',
    'premium.feature.films': 'Rare films and filters',
    'premium.feature.highlights': 'Up to 10 frames in the profile film strip',
    'premium.feature.badge': 'Premium badge in your profile',
    'premium.feature.early': 'Early access to new features',
    'premium.feature.support': 'Priority support',

    'music.enable': 'Turn on music',
    'music.close': 'Close player',
    'music.previous': 'Previous track',
    'music.pause': 'Pause',
    'music.play': 'Play',
    'music.next': 'Next track',

    'filmPicker.title': 'Load film',
    'filmPicker.hint': 'Choose film for shooting',
    'filmPicker.load': 'Load',
    'filmHeader.open': 'Open',
    'filmHeader.replace': 'Replace',
    'filmHeader.remove': 'Remove',
  },
}

function normalizeLanguage(raw: string | null | undefined): AppLanguage {
  return raw?.toLowerCase().startsWith('ru') ? 'ru' : 'en'
}

function getTelegramLanguage(): string | null {
  return getTelegramUser()?.language_code ?? null
}

function getStoredLanguage(): AppLanguage | null {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    return stored === 'ru' || stored === 'en' ? stored : null
  } catch {
    return null
  }
}

function detectLanguage(): AppLanguage {
  const telegramLanguage = getTelegramLanguage()
  if (telegramLanguage) return normalizeLanguage(telegramLanguage)
  return normalizeLanguage(navigator.language)
}

function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template
  return Object.entries(params).reduce(
    (text, [key, value]) => text.split(`{{${key}}}`).join(String(value)),
    template,
  )
}

export function translate(language: AppLanguage, key: string, params?: Record<string, string | number>): string {
  return interpolate(translations[language][key] ?? translations.en[key] ?? key, params)
}

export function formatRelativeTime(iso: string, language: AppLanguage): string {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 2) return translate(language, 'time.now')
  if (mins < 60) return translate(language, 'time.minutesAgo', { count: mins })
  const hours = Math.floor(mins / 60)
  if (hours < 24) return translate(language, 'time.hoursAgo', { count: hours })
  if (hours < 48) return translate(language, 'time.yesterday')
  return translate(language, 'time.daysAgo', { count: Math.floor(hours / 24) })
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [detectedLanguage, setDetectedLanguage] = useState<AppLanguage>(() => detectLanguage())
  const [language, setLanguageState] = useState<AppLanguage>(() => getStoredLanguage() ?? detectLanguage())

  useEffect(() => {
    const detected = detectLanguage()
    setDetectedLanguage(detected)
    if (!getStoredLanguage()) setLanguageState(detected)
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    detectedLanguage,
    t: (key, params) => translate(language, key, params),
    setLanguage: (nextLanguage) => {
      setLanguageState(nextLanguage)
      try {
        localStorage.setItem(STORAGE_KEY, nextLanguage)
      } catch {
        // Ignore storage errors in restricted WebViews.
      }
    },
  }), [detectedLanguage, language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
